### ISSUE TITLE
Serialcommand issue

### ISSUE THREAD

**Issue by nicofly** [pepsilla/Arduino#1]
I'm trying to use your modbus implementation, but i receive this strange error message
AsciiModbusMasterArduino:93:14: error: 'class SerialCommand' has no member named 'addDefaultHandler'
   _myMonitor.addDefaultHandler(miMonitor);//Default handler ex:for decive information
              ^
exit status 1
'class SerialCommand' has no member named 'addDefaultHandler'

Which serialcommand library do you use ?

**Comment by pepsilla** [comment]
https://github.com/pepsilla/ArduinoSerialCommand/blob/master/SerialCommand.h

And define SERIALCOMMAND_HARDWAREONLY on line 52.
